# Generated by Django 3.2.6 on 2022-01-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='profile_picture',
        ),
    ]
