# Generated by Django 3.2.6 on 2021-12-16 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students'),
        ),
        migrations.AddField(
            model_name='school_assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.courses'),
        ),
        migrations.AddField(
            model_name='school_assignment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.topic'),
        ),
        migrations.AddField(
            model_name='history',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.content'),
        ),
        migrations.AddField(
            model_name='history',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.courses'),
        ),
        migrations.AddField(
            model_name='history',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students'),
        ),
        migrations.AddField(
            model_name='history',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.topic'),
        ),
        migrations.AddField(
            model_name='events',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolyears'),
        ),
        migrations.AddField(
            model_name='courses',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolyears'),
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.topic'),
        ),
        migrations.AddField(
            model_name='comments',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.events'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
