# Generated by Django 3.2.6 on 2021-12-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='year',
        ),
    ]
