# Generated by Django 3.2.6 on 2021-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_admins_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
    ]
