# Generated by Django 3.2.6 on 2021-09-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210913_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyears',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
