# Generated by Django 3.2.6 on 2021-09-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_schoolyears_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolyears'),
        ),
    ]
