# Generated by Django 3.2.6 on 2021-09-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_students_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='course',
        ),
    ]
