# Generated by Django 3.2.6 on 2021-09-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210918_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='user',
            new_name='sender',
        ),
    ]
