# Generated by Django 3.2.6 on 2021-09-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_user_notifications_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='reply',
            new_name='parents',
        ),
    ]
