# Generated by Django 3.2.6 on 2021-09-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_reply_comments_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parents',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.content')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.students')),
            ],
        ),
    ]
