# Generated by Django 3.2.6 on 2021-09-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210922_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.coursecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.courses'),
            preserve_default=False,
        ),
    ]
