# Generated by Django 3.2.6 on 2021-09-23 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210923_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
