# Generated by Django 3.2.6 on 2021-09-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_history_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='HS_diploma',
            field=models.FileField(blank=True, null=True, upload_to='students'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students'),
        ),
    ]
