# Generated by Django 3.2.6 on 2021-09-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210924_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='category',
            new_name='topic',
        ),
        migrations.RenameModel(
            old_name='CourseCategory',
            new_name='CourseTopic',
        ),
        migrations.CreateModel(
            name='ClassWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/classwork/assignment/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teachers')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.courses')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main_app.classwork')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coursetopic')),
            ],
        ),
    ]
