# Generated by Django 3.2.6 on 2021-09-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_category_id_history_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classwork',
            name='year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.schoolyears'),
            preserve_default=False,
        ),
    ]
