# Generated by Django 3.2.6 on 2021-09-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210927_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_picture',
            field=models.ImageField(blank=True, null=True, upload_to='course/<django.db.models.fields.CharField>/course_picture'),
        ),
    ]
