# Generated by Django 3.2.6 on 2021-09-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_courses_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_picture',
            field=models.ImageField(blank=True, null=True, upload_to='course/course.__str__/course_picture'),
        ),
    ]
