# Generated by Django 3.2.6 on 2021-09-27 22:10

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_courses_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_location),
        ),
    ]
