# Generated by Django 3.2.6 on 2021-09-27 22:56

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_content_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_location_admins),
        ),
        migrations.AlterField(
            model_name='applications',
            name='HS_diploma',
            field=models.FileField(blank=True, null=True, upload_to=main_app.models.upload_location_students),
        ),
        migrations.AlterField(
            model_name='applications',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_location_students),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main_app.models.upload_location_assignment),
        ),
        migrations.AlterField(
            model_name='students',
            name='HS_diploma',
            field=models.FileField(blank=True, null=True, upload_to=main_app.models.upload_location_students),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_location_students),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_location_teachers),
        ),
    ]
