# Generated by Django 3.2.6 on 2021-09-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210927_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.courses'),
        ),
    ]
