# Generated by Django 3.2.6 on 2021-10-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_studentworks_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentworks',
            old_name='asignment',
            new_name='assignment',
        ),
    ]
