# Generated by Django 3.2.6 on 2021-10-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_rename_asignment_studentworks_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentworks',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classwork'),
        ),
    ]
