# Generated by Django 3.2.6 on 2021-10-02 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_studentworks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentworks',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
