# Generated by Django 3.2.6 on 2021-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_studentworks_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentworks',
            name='status',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Unchecked', 'Unchecked'), ('Failed', 'Failed')], default='Unchecked', max_length=10, null=True),
        ),
    ]
