# Generated by Django 3.2.6 on 2021-10-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_studentworks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='unread',
        ),
    ]
