# Generated by Django 3.2.6 on 2021-10-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_notifications_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='courses',
        ),
    ]
