# Generated by Django 3.2.6 on 2021-10-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_remove_teachers_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.courses'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
