# Generated by Django 3.2.6 on 2021-10-04 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_auto_20211004_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='unique_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
