# Generated by Django 3.2.6 on 2021-12-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_notifications_unique_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='HS_diploma',
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
